services:
  - type: web
    name: delta-strangle-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python waitress_server.py
    envVars:
      - key: DELTA_API_KEY
        sync: false
      - key: DELTA_API_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    
